[phases.setup]
nixPkgs = ["nodejs_22", "python311"]

[phases.build]
cmds = [
  "cd frontend && rm -rf node_modules package-lock.json",
  "cd frontend && npm install",
  "cd frontend && npm run build"
]

[start]
cmd = "cd frontend && npm run preview"
